osx_instance:
  image: mojave-xcode-10.2-flutter

container:
  image: cirrusci/flutter:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test

build_android_task:
  depends_on:
    -test
  build_android_script: flutter build apk --release
  android_artifacts: 
    path: "build/app/outputs/apk/release/app-release.apk"

build_ios_task:
  depends_on:
    -test
  build_ios_script: flutter build ios --release --no-codesign
  ios_artifacts:
    path: "ios/Runner.ipa"